version: '3.8'

services:
  django:
    build:
      context: docker/python
    volumes:
      - ./src/keiyakusha:/src
      - ./tests:/tests
    stdin_open: true
    tty: true
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: '["0.0.0.0"]'
    command: |
      sh -c "./manage.py wait_for_db && ./manage.py runserver 0.0.0.0:34763"
    ports:
      - 34763:34763

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: 'keiyakusha_password'
      POSTGRES_USER: 'keiyakusha'
      POSTGRES_DB: 'keiyakusha_db'
    ports:
      - '41881:5432'
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
