version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'keiyakusha'
      POSTGRES_DB: 'keiyakusha_db'
    ports:
      - '41881:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
