# Generated by Django 2.1 on 2018-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('external_reference', 'project')},
        ),
    ]
